# Generated by Django 6.0.3 on 2026-07-16 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0006_laborder_report_file'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalariaScreen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='malaria_screens/%Y/%m/')),
                ('ai_label', models.CharField(blank=True, max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_model_version', models.CharField(blank=True, max_length=100)),
                ('ai_raw_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting confirmation'), ('confirmed_positive', 'Confirmed: Positive'), ('confirmed_negative', 'Confirmed: Negative'), ('overridden', 'Overridden by scientist'), ('inconclusive', 'Inconclusive')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('scientist_notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malaria_confirmations', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malaria_screens', to='lab.laborderitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malaria_screens', to='patients.patient')),
            ],
            options={
                'db_table': 'malaria_ai_screens',
                'ordering': ['-created_at'],
            },
        ),
    ]
