# Generated by Django 6.0.3 on 2026-07-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malariascreen',
            name='test_type',
            field=models.CharField(default='malaria', max_length=40),
        ),
        migrations.AlterField(
            model_name='malariascreen',
            name='ai_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='MalariaScreenBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('predicted_class', models.CharField(max_length=40)),
                ('source', models.CharField(choices=[('ai', 'AI proposed'), ('human', 'Human added')], max_length=10)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='malaria_ai.malariascreen')),
            ],
            options={
                'db_table': 'malaria_ai_screen_boxes',
            },
        ),
    ]
