# Generated by Django 6.0.3 on 2026-05-13 13:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0001_initial'),
        ('pharmacy', '0002_remove_drug_current_stock_drugbatch_stockalert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='discharged_at',
        ),
        migrations.AddField(
            model_name='admission',
            name='requested_ward_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='ipd.bed'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='requested', max_length=15),
        ),
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ipd.admission')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ipd_room_records',
            },
        ),
        migrations.CreateModel(
            name='RoomMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='ipd.roomrecord')),
            ],
            options={
                'db_table': 'ipd_room_medications',
            },
        ),
    ]
