# Generated by Django 6.0.3 on 2026-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '003_bed_prce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='requested', max_length=15),
        ),
    ]
