# Generated by Django 6.0.3 on 2026-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_prescriptionitem_dispense_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, default='tablet', max_length=30),
        ),
        migrations.AddField(
            model_name='drug',
            name='interactions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='rx_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
