# Generated by Django 6.0.3 on 2026-07-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_drug_barcode_drug_dosage_form_drug_interactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='balance_after',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
