# Generated by Django 6.0.3 on 2026-07-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_stocktransaction_balance_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('partial', 'Partial'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
