# Generated by Django 6.0.3 on 2026-06-12 02:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('booking_date', models.DateField(default=django.utils.timezone.localdate)),
                ('lmp', models.DateField(help_text='Last menstrual period')),
                ('gravida', models.PositiveIntegerField(default=1)),
                ('para', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low risk'), ('high', 'High risk')], default='low', max_length=5)),
                ('risk_factors', models.TextField(blank=True)),
                ('tt_doses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anc_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_enrollments', to='patients.patient')),
            ],
            options={
                'db_table': 'anc_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('fundal_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('urine_protein', models.CharField(blank=True, choices=[('', '—'), ('neg', 'Negative'), ('trace', 'Trace'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+')], max_length=6)),
                ('complaints', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='maternity.ancenrollment')),
                ('seen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anc_visits_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anc_visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delivery_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('svd', 'SVD (vaginal)'), ('cs', 'Caesarean section'), ('assisted', 'Assisted (vacuum/forceps)')], default='svd', max_length=10)),
                ('outcome', models.CharField(choices=[('live', 'Live birth'), ('stillbirth', 'Stillbirth')], default='live', max_length=10)),
                ('baby_sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('apgar_1min', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_5min', models.PositiveIntegerField(blank=True, null=True)),
                ('complications', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_conducted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='maternity.ancenrollment')),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-delivery_datetime'],
            },
        ),
    ]
