# Generated by Django 4.2.9 on 2026-03-21 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC')], max_length=2)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of known allergies')),
                ('insurance_provider', models.CharField(choices=[('none', 'None / Self-Pay'), ('nhis', 'NHIS'), ('axa', 'AXA Mansard'), ('hygeia', 'Hygeia HMO'), ('aiico', 'AIICO'), ('other', 'Other')], default='none', max_length=20)),
                ('insurance_id', models.CharField(blank=True, max_length=50)),
                ('hmo_plan', models.CharField(blank=True, max_length=50)),
                ('emergency_name', models.CharField(blank=True, max_length=150)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('past_surgeries', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('vaccination_history', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Medical Histories',
                'db_table': 'medical_histories',
            },
        ),
    ]
