# Generated by Django 4.2.9 on 2026-03-21 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('session_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('consult_type', models.CharField(choices=[('video', 'Video Call'), ('voice', 'Voice Call'), ('async', 'Async / Chat')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting Room'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('chief_complaint', models.TextField(blank=True)),
                ('notify_via', models.CharField(choices=[('sms_email', 'SMS + Email'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sms_email', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=255)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('clinical_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tele_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'tele_sessions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sender_label', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=20)),
                ('message', models.TextField()),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telemedicine.telesession')),
            ],
            options={
                'db_table': 'session_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('drugs', models.JSONField(default=list, help_text='[{name, dose, frequency, duration}]')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('dispensed', 'Dispensed')], default='sent', max_length=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eprescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eprescriptions', to='patients.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprescriptions', to='telemedicine.telesession')),
            ],
            options={
                'db_table': 'eprescriptions',
            },
        ),
    ]
