# Generated by Django 6.0.3 on 2026-05-27 15:18

from django.db import migrations, models
import secrets

def _populate_join_tokens(apps, schema_editor):
    TeleSession = apps.get_model('telemedicine', 'TeleSession')
    for s in TeleSession.objects.all():
        if not s.join_token:
            s.join_token = secrets.token_urlsafe(48)
            s.save(update_fields=['join_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0002_alter_telesession_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telesession',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='telesession',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telesession',
            name='join_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.RunPython(_populate_join_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='telesession',
            name='join_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
