# Generated by Django 6.0.3 on 2026-05-12 11:45

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborder',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='laborder',
            old_name='ordered_by',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='laborder',
            old_name='clinical_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='labtest',
            old_name='reference_range',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='collected_at',
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='laborderitem',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='laborderitem',
            name='finalized_at',
        ),
        migrations.RemoveField(
            model_name='laborderitem',
            name='finalized_by',
        ),
        migrations.RemoveField(
            model_name='laborderitem',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='turnaround_hours',
        ),
        migrations.AddField(
            model_name='laborder',
            name='billing_invoice_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='reference_range_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='reference_range_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='remarks',
            field=models.TextField(blank=True, help_text="Technologist's remarks, e.g. 'hemolyzed sample'"),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='result_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value for calculations', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='result_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='sample_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='sample_status',
            field=models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Collected'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='requires_fasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='turnaround_time_hours',
            field=models.PositiveIntegerField(default=24, help_text='Expected TAT in hours'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='unit',
            field=models.CharField(default=datetime.datetime(2025, 12, 31, 23, 0, tzinfo=datetime.timezone.utc), help_text='e.g. test, ml, slide', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=15),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.laborder'),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='result_value',
            field=models.TextField(blank=True, help_text='Numeric or descriptive result'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology'), ('urinalysis', 'Urinalysis'), ('histopathology', 'Histopathology'), ('imaging', 'Imaging'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='LabResultHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lab.laborderitem')),
            ],
            options={
                'db_table': 'lab_result_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('sample_type', models.CharField(max_length=50)),
                ('sample_volume', models.CharField(blank=True, max_length=20)),
                ('container_type', models.CharField(blank=True, max_length=50)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='lab.laborderitem')),
            ],
            options={
                'db_table': 'sample_collections',
            },
        ),
    ]
