# Generated by Django 6.0.3 on 2026-05-24 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_laborder_options_alter_labtest_options_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='billing_invoice_id',
        ),
        migrations.AddField(
            model_name='laborder',
            name='clinical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT — Immediate')], default='routine', max_length=10),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='flag',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('H', 'High'), ('L', 'Low'), ('HH', 'Critical High'), ('LL', 'Critical Low'), ('A', 'Abnormal'), ('P', 'Positive'), ('N', 'Negative')], max_length=10),
        ),
        migrations.AddField(
            model_name='labresulthistory',
            name='action',
            field=models.CharField(choices=[('result_entry', 'Result Entry'), ('amendment', 'Amendment'), ('approval', 'Approval'), ('rejection', 'Rejection')], default='result_entry', max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_note',
            field=models.CharField(blank=True, help_text='e.g. Adult Male: 13.5–17.5, Female: 12–16', max_length=200),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_range_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_range_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labtest',
            name='specimen_type',
            field=models.CharField(choices=[('blood_edta', 'Blood (EDTA)'), ('blood_plain', 'Blood (Plain)'), ('blood_fluoride', 'Blood (Fluoride Oxalate)'), ('urine', 'Urine'), ('stool', 'Stool'), ('sputum', 'Sputum'), ('swab', 'Swab'), ('csf', 'CSF'), ('tissue', 'Tissue/Biopsy'), ('none', 'None (ECG/Scan)')], default='blood_edta', max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='times_performed',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='condition',
            field=models.CharField(blank=True, choices=[('acceptable', 'Acceptable'), ('haemolyzed', 'Haemolyzed'), ('lipemic', 'Lipemic'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='result_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='result_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology/Immunology'), ('urinalysis', 'Urinalysis'), ('histopathology', 'Histopathology'), ('imaging', 'Imaging/Radiology'), ('ecg', 'ECG/Cardiology'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='turnaround_time_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. g/dL, mmol/L, ×10³/µL', max_length=30),
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_cover', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('part_paid', 'Part Paid'), ('paid', 'Paid'), ('waived', 'Waived'), ('insurance', 'Insurance')], default='unpaid', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('pos', 'POS / Card'), ('transfer', 'Bank Transfer'), ('nhis', 'NHIS / HMO'), ('waived', 'Waived')], max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='lab.laborder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bills', to='patients.patient')),
            ],
            options={
                'db_table': 'lab_bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='lab.labbill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtest')),
            ],
            options={
                'db_table': 'lab_bill_items',
            },
        ),
        migrations.CreateModel(
            name='LabPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS / Card'), ('transfer', 'Bank Transfer'), ('nhis', 'NHIS / HMO'), ('waived', 'Waived')], max_length=10)),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lab.labbill')),
            ],
            options={
                'db_table': 'lab_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInventoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='lab.labtest')),
            ],
            options={
                'db_table': 'lab_service_inventory',
                'ordering': ['-date', 'test__category'],
                'unique_together': {('test', 'date')},
            },
        ),
    ]
