# Generated by Django 6.0.3 on 2026-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_labtest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
