# Generated by Django 6.0.3 on 2026-05-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_labtest_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='paid',
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
