# Generated by Django 6.0.3 on 2026-06-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_remove_labtest_paid_laborderitem_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/%Y/%m/'),
        ),
    ]
