# Generated by Django 6.0.3 on 2026-07-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('lab', '0006_laborder_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbill',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_bill_link', to='billing.invoice'),
        ),
    ]
