# Generated by Django 6.0.3 on 2026-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_labbill_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='ai_test_type',
            field=models.CharField(blank=True, help_text='Matches a Model.', max_length=40),
        ),
    ]
